server:
  port: 8080

spring:
  jpa:
    database-platform: com.spring.security.config.SQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:security.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  thymeleaf:
    prefix: classpath:/templates/views/
    check-template-location: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(n8JfPcEZmm8b/Tp8A3AKVRNitLXrFnIZMNBrT8iOC0Uv1IfDVJLC2gDT4xWzxmDdCQew2XGxWfZhYYC8LFxSKH/zUcA8EsgHEcF731rGauHyc80TGlmG3A==)
            client-secret: ENC(7m+6iuDVIrWhh85iEsqIcjFWWHTtm8VRh1u8BGU56BYCWAX6Mk1+O9YnZOv97izS)
            scope: email,profile
          github:
            client-id: ENC(QCl4EFArVd53I1iEkpCet8NWf3ULc4hdxrcdTwxGNOs=)
            client-secret: ENC(+ENO6U1bmeYQt3fpPlpPVWxOdChzKQgwqu8iyIAzsGdZd0H/XihYZ4q93MUX8dZhoPPkgefwlZQ=)
          kakao:
            client-id: ENC(9oxHNIXTGqi6cpzp3zoYEtfygfDTHINCK6zSzjgRYGKb2l4vAajCFhf4Jq4Rk2ZA)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
          naver:
            client-id: ENC(V2lvFw+eySunVNghn1iDGSyeZuqv3Ma38efvSAhafnA=)
            client-secret: ENC(LvwXryparoqo5RpbwzfKuHRQyKjjp1Fm)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: info

security:
  setting:
    factor:
      password: true
      oauth2: false
      jwt: false
